[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "."